import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark transition-colors delay-1000 duration-300 ease-in-out">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
